FROM python:3.9.6-alpine

WORKDIR /django

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev bash

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY entrypoint.sh .
RUN sed -i 's/\r$//g' /django/entrypoint.sh
RUN chmod +x /django/entrypoint.sh

COPY . .

ENTRYPOINT ["/django/entrypoint.sh"]
